id: P001779
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30049
  title: སོ་ལྟ་དང་གཟབ་ཉན།
  author: ''
  volumes:
    1238fd68c3bc4ebdb7a8b955b8500560:
      image_group_id: I1KG12342
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
